name: capstone2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  flutter_web_auth: ^0.6.0
  dio: ^5.7.0
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1
  firebase_storage: ^12.3.3
  firebase_dynamic_links: ^6.0.8
  http: ^1.2.2
  url_launcher: ^6.3.1
  flutter_appauth: ^8.0.0+1
  firebase_analytics: ^11.3.3
  go_router: ^14.3.0
  flutter_secure_storage: ^9.2.2
  spotify: ^0.13.7

  animated_snack_bar: ^0.4.0
  auth_health_flutter :
    git:
      url: https://github.com/hassaanahmed113/auth_health_flutter.git
  camera: ^0.11.0+2
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image.png
    - assets/images/image_4.png
    - assets/images/image_3.png
    - assets/images/image_6.png
    - assets/images/image_9.png
    - assets/images/image_5.png
    - assets/vectors/ellipse_4_x2.svg
    - assets/vectors/ellipse_5_x2.svg
    - assets/images/image_7.png
    - assets/images/image_2.png
    - assets/images/image_8.png
    - assets/images/image_3.png
    - assets/images/image_10.png
    - assets/images/image_1.png
    - assets/vectors/ellipse_1_x2.svg
    - assets/vectors/ellipse_3_x2.svg
    - assets/background/login.png
    - assets/background/forget.png
    - assets/background/sync.png
    - assets/background/homeScreen.png
    - assets/images/account.jpg
    - assets/background/img.png
